Rewrite
npm/proc-log pull request #77
Opened 2024-04-11 17:04 UTC by wraithgar

This is a rewrite of proc-log

- **feat!: change current exported function "log"**
    Everything that's currently in proc-log is now exported as a `log` object
- **fix(refactor): don't loop through levels to generate log export**
    The entire module is inline, no loops.  Tests ensure that we are synced between levels and methods.
- **feat(log): add timing log level**
    A new `timing` log level has been added
- **feat: add output methods**
    A new `output` export has been added with three levels: `standard`, `error`, and `buffer`. It works exactly like the `log` object but emits `output` events.

2024-04-11 17:10 UTC, lukekarrys commented on README.md
> +  This is for general standard output.  Consumers will typically show this on stderr (after optionally formatting or filtering it).
```suggestion
  This is for general error output.  Consumers will typically show this on stderr (after optionally formatting or filtering it).
```

2024-04-11 17:10 UTC, lukekarrys commented on test/index.js
> +for (method in procLog) {
```suggestion
for (const method in procLog) {
```

2024-04-11 17:16 UTC, wraithgar commented on test/index.js
> +for (method in procLog) {
I promise I'm a professional programmer.

2024-04-11 19:57 UTC, fritzy requested changes

2024-04-11 19:57 UTC, fritzy commented on test/index.js
> +    const { LEVELS } = log
This tests that the methods and log levels match, but it feels a bit fragile. We're testing that things are internally consistent, but if there's a bug in this test, we wouldn't know that it's not testing the breadth of level/functions we expect. Even a simple `LEVELS.length >= 10` assertion would prove that we're looping through and testing _something_.

2024-04-11 20:27 UTC, wraithgar commented on test/index.js
> +    const { LEVELS } = log
We snapshot the levels to make sure there's something there

```
t.matchSnapshot(LEVELS, `${method} levels`)
```

2024-04-11 20:29 UTC, wraithgar commented on test/index.js
> +    const { LEVELS } = log
a `t.plan` could make sure we're testing the expected two top level methods?

2024-04-11 20:31 UTC, wraithgar commented on test/index.js
> +    const { LEVELS } = log
```js
const procLog = require('../')
// This makes sure we are testing the two known exported methods.
t.plan(2)
for (const method in procLog) {
```

2024-04-11 20:31 UTC, wraithgar commented on test/index.js
> +    const { LEVELS } = log
Or we can snapshot `Object.keys(procLog)`?

2024-04-11 21:04 UTC, fritzy commented on test/index.js
> +    const { LEVELS } = log
I didn't notice the snapshot of `LEVELS`. Approving...

2024-04-11 21:04 UTC, fritzy submitted a review, later dismissed
👍

2024-04-11 21:06 UTC, wraithgar commented on test/index.js
> +    const { LEVELS } = log
tap snapshots are weird in that if I removed a level, that snapshot would live in the snapshot file with no errors. I am adding the `t.plan(2)` we we at least are asserting that we have two main exports before we iterate throught them.

2024-04-11 21:38 UTC, fritzy approved these changes

2024-04-12 01:47 UTC, lukekarrys approved these changes

2024-04-12 14:06 UTC, merged